### ISSUE TITLE
KUBECONFIG is the worst possible env var name for install-kubeconfig

### ISSUE THREAD

**Issue by ochronus** [CircleCI-Public/kubernetes-orb#33]
### Orb version
1.0.0

### What happened
The install-kubeconfig section of the doc (and the source!) suggests KUBECONFIG as an env var to hold the base64 encoded kubernetes cluster config (also I need to look at the source to see that I need to base64 encode it). This causes all subsequent kubectl commands to fail as kubectl uses the same env variable to store the _path to the config file_ - which is now a base64 encoded blob. 

### Expected behavior
The doc should suggest a different default name to hold the base64 encoded kubeconfig
The default for that variable should be different
The doc should state it needs to be base64 encoded

**Comment by lokst** [comment]
@ochronus Thank you for your feedback! I agree that the naming of the default environment variable for `install-kubeconfig` is not ideal at all. We'll fix that and also improve the documentation for the command.

**Comment by ochronus** [comment]
Sounds great, thanks for the quick reaction!
💕🙏

**Comment by lokst** [comment]
@ochronus This is now resolved in version `0.11.0` of the orb 🙂

**Comment by ochronus** [comment]
Amazing news, thank you so much!!
