### ISSUE TITLE
examples contain wrong orb name in the steps

### ISSUE THREAD

**Issue by puja108** [CircleCI-Public/kubernetes-orb#35]
### Orb version

0.11.0

### What happened

I tried out the examples, e.g. https://github.com/CircleCI-Public/kubernetes-orb/blob/master/src/examples/deployment-update.yml

### Expected behavior

Circle was reporting errors that an orb named `kube-orb` cannot be found.

Replacing occurences of `kube-orb` to `kubernetes` fixed the build.

If you want, I can provide a PR to fix the examples.

**Comment by lokst** [comment]
Hi @puja108, the example you linked to looks right to me. Could it be that the reference to the kubernetes orb in your config.yml was named `kubernetes` rather than `kube-orb` as in the example?

```
orbs:
    kubernetes: circleci/kubernetes@x.y.z
```

instead of:

```
orbs:
    kube-orb: circleci/kubernetes@x.y.z
```

**Comment by puja108** [comment]
Found the issue. I got the example from https://circleci.com/orbs/registry/orb/circleci/kubernetes, but I used the orb as it is mentioned in the first few lines of that doc, and there, unlike in the examples it is indeed named “kubernetes”, and then in the example that changes to be “kube-orb”, but if people, like me, already imported the orb in the first line into their existing config, then using part of an example from below will result in a mismatch of names.

Not sure where you keep the first section of the docs, but having a coherent naming across the docs intro and the examples would avoid confusion.

Anyway, minor nitpick here, feel free to fix or close.

**Comment by WillGibson** [comment]
I got caught out by this too. The issue is simply that the quick start guide declares the orb differently than the examples. I'm happy to submit a PR too, but not sure whether it would be preferred to update the examples to match the quick start guide or vice versa?

**Comment by lokst** [comment]
Thanks so much @WillGibson, if you could submit a PR it would be great. I think it'd be best for the examples to match the quick start guide.
