### ISSUE TITLE
[feature request] - Support `server_api` and `token` directive

### ISSUE THREAD

**Issue by rturk** [CircleCI-Public/kubernetes-orb#4]
### Orb version

Latest version

### What happened

Feature request. My K8S server is running on AWS (based on Kops)

### Expected behavior

Support full featured `kubectl` commands, in order to achieve something like

      kubectl --namespace=${K8S_NAMESPACE} --server=${K8S_STAGING_MASTER} --token=${KS8_STAGING_TOKEN} --insecure-skip-tls-verify=true set image deployment/${K8S_DEPLOYMENT} ${IMAGE_NAME}=${REGISTRY}/${IMAGE_NAME}:${CIRCLE_SHA1}-staging

**Comment by iynere** [comment]
i think, for now, the idea is that this orb just simplifies the process of _installing_ kubectl, & then from there you can just run any commands that you want @rturk 

after all, if you already know the `kubectl` command you want to run, doing it like this:

```
- run: |
     kubectl \
      --namespace=${K8S_NAMESPACE} \
      --server=${K8S_STAGING_MASTER} \
      --token=${KS8_STAGING_TOKEN} \
      --insecure-skip-tls-verify=true \
      set image deployment/${K8S_DEPLOYMENT} \
      ${IMAGE_NAME}=${REGISTRY}/${IMAGE_NAME}:${CIRCLE_SHA1}-staging
```

is pretty easy, right ?

that said, while i don't think we could reasonably wrap the entirety of the `kubectl` CLI's functionality via this orb, is there perhaps a middleground that would make what you're trying to do easier ?

e.g., maybe a `kube-set-image-deployment` command or something like that ? 

thank you!

**Comment by rturk** [comment]
@iynere tks!
