### ISSUE TITLE
Bash warning during create-update-resource

### ISSUE THREAD

**Issue by AlanRaisonNews** [CircleCI-Public/kubernetes-orb#48]
## What happened:

During create-update-resource, there is an error in the script, which produces the error:

```
/bin/bash: line 10: [: missing `]'
```

Presumably this is preventing the server side apply parameter from working.

## Expected behavior:

No error; server side apply parameter works.

**Comment by brivu** [comment]
This issue was fixed in this PR: [Fix server side apply option #43](https://github.com/CircleCI-Public/kubernetes-orb/pull/43)
