### ISSUE TITLE
Rollout Status should allow a manifest instead of resource name

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/kubernetes-orb#49]
## Describe Request:
`kubectl rollout status`, like apply will accept an `-f` flag identifying the resource.

We accept it for apply, but not status. And adding `get-rollout-status: true` should use the manifest we already passed to same orb command.

## Examples:
Example pipelines generate the manifest in earlier steps.  Since we are using Vamp release orchestration the deployment name is unique to each deployment, so to hardcode in config.yml is copy-pasta.

- Failed build because I didnt add resource name 
https://app.circleci.com/pipelines/github/eddiewebb/demo-blueskygreenbuilds/378/workflows/79e4c791-0859-46df-afcf-973264e7d845/jobs/2462
- passing build using `kubectl rollout status -f` instead
https://app.circleci.com/pipelines/github/eddiewebb/demo-blueskygreenbuilds/379/workflows/de825702-5d27-4925-a2e1-da7a504ba8cc/jobs/2467

## Supporting Documentation Links:
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-status-em-

**Comment by brivu** [comment]
Hey @eddiewebb, 

I'm working on this orb now and will look to add this request.  Stay tuned! 

Best, 
Brian
