### ISSUE TITLE
[request] Separate commands `install kops` & `install kubectl`

### ISSUE THREAD

**Issue by zackijack** [CircleCI-Public/kubernetes-orb#5]
### Orb version

0.3.0

### What happened

Sometimes we just need to install `kubectl` without `kops`, the current command can't do that, because both of them are in 1 command.

### Expected behavior

Separates into 2 commands, so when you only need `kubectl`, it can save execution time.

**Comment by iynere** [comment]
thank you ! should be an easy fix—

- create `install-kops` command
- create `install-kubectl` command
- refactor `install` command with `boolean` parameters for `install-kops` & `install-kubectl`

wanna take a shot at a pr ? @zackijack

**Comment by zackijack** [comment]
@iynere sure, thanks
