### ISSUE TITLE
Examples should be simple and use case driven

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/kubernetes-orb#9]
### Orb version

0.3.0

### What happened

Found a bunch of commands that were unclear purpose

### Expected behavior

Expected to find a simple "update" or "deploy" orb example

### more
Current example https://circleci.com/orbs/registry/orb/circleci/kubernetes#usage-deployment
1) we shouldnt need minukube to deploy, thats a testing use case right?
2) The deploy example should not delete resources
3)we should be clear about the different intentions of apply, update, etc

**Comment by j-collier** [comment]
I think the example uses Minikube to deploy because it's the easiest to demonstrate and not that it's a requirement for deploying to production kubernetes clusters. Can I take this one and attempt to clarify the examples?
